---
- name: nginx
  hosts: [NGINX]
  become: true
  become_method: sudo
  tasks:
   - name: Install nginx
     apt: name=nginx state=latest
   - name: service1
     service: name=nginx state=started



- name: Apache
  hosts: [Apache]
  become: true
  become_method: sudo
  tasks:
   - name: Install Apache
     apt: name=apache2 state=latest
   - name: service2
     service: name=apache2 state=started

# handlers file
